### ISSUE TITLE
Migrate to Angular

### ISSUE THREAD

**Issue by fredmabire** [MomsFriendlyDevCo/angular-ui-query-builder#13]
Hi,

I would like to know if you plan to migrate this library to Angular ?

**Comment by hash-bang** [comment]
@fredmabire, unfortunately no.

This component was developed some time ago in Angular@1 and we, the company who built it, have moved to the Vue framework rather than Angular@2+.

This component is used in one or two of our older projects so will still get the odd patch but I doubt it will be receiving any major updates.
